### ISSUE TITLE
Grunt issues

### ISSUE THREAD

**Issue by mnzt** [benkaiser/stretto#83]
```
root@mnzt:~/stretto# grunt
Loading "grunt-bower-install-simple.js" tasks...ERROR
>> Error: Cannot find module 'q'
Warning: Task "bower-install-simple:def" not found. Use --force to continue.

Aborted due to warnings.
```

From a fresh git clone. 

Other modules missing are; `mout, configstore, archy, semver-utils, stringify-object, semver-utils, graceful-fs, handlebars`.

After install all these modules with `npm i [module]` I'm then greeted with the following Grunt error:
```
root@gopee:~/stretto# grunt
Running "bower-install-simple:def" (bower-install-simple) task
Executing Bower (Command: install)
Warning: Cannot find module 'glob' Use --force to continue.

Aborted due to warnings.
```

This also throws this error for the following packages; `rimraf, chmodr, md5-hex, retry, lru-cache, lockfile, semver, fstream, fstream-ignore, which, tmp, p-throttler, request-progress, fs-write-stream-atomic, destroy, decompress-zip, tar-fs, shell-quote` After manually installing all of these packages, grunt runs and resolves most assets, before hitting another snag:

```
bower error         cmd(...).spread is not a function

Stack trace:
TypeError: cmd(...).spread is not a function
    at Function.GitRemoteResolver.refs (/root/stretto/node_modules/grunt-bower-i                        nstall-simple/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:255:6)
    at Function.GitResolver.tags (/root/stretto/node_modules/grunt-bower-install                        -simple/node_modules/bower/lib/core/resolvers/GitResolver.js:297:18)
    at Function.GitResolver.versions (/root/stretto/node_modules/grunt-bower-ins                        tall-simple/node_modules/bower/lib/core/resolvers/GitResolver.js:257:18)
    at GitHubResolver.GitResolver._findResolution (/root/stretto/node_modules/gr                        unt-bower-install-simple/node_modules/bower/lib/core/resolvers/GitResolver.js:10                        6:21)
    at GitHubResolver.GitRemoteResolver._findResolution (/root/stretto/node_modu                        les/grunt-bower-install-simple/node_modules/bower/lib/core/resolvers/GitRemoteRe                        solver.js:99:50)
    at GitHubResolver.GitResolver._resolve (/root/stretto/node_modules/grunt-bow                        er-install-simple/node_modules/bower/lib/core/resolvers/GitResolver.js:65:17)
    at _fulfilled (/root/stretto/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/root/stretto/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/root/stretto/node_modules/q/q.js:796:13                        )
    at /root/stretto/node_modules/q/q.js:604:44

Console trace:
Error
    at StandardRenderer.error (/root/stretto/node_modules/grunt-bower-install-si                        mple/node_modules/bower/lib/renderers/StandardRenderer.js:83:37)
    at Logger.<anonymous> (/root/stretto/node_modules/grunt-bower-install-simple                        /tasks/grunt-bower-install-simple.js:119:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/root/stretto/node_modules/grunt-bower-install-simple/node_m                        odules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /root/stretto/node_modules/grunt-bower-install-simple/node_modules/bower/                        lib/commands/index.js:48:20
    at _rejected (/root/stretto/node_modules/q/q.js:844:24)
    at /root/stretto/node_modules/q/q.js:870:30
    at Promise.when (/root/stretto/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/root/stretto/node_modules/q/q.js:788:41                        )
System info:
Bower version: 1.7.2
Node version: 4.2.4
OS: Linux 3.13.0-68-generic x64
Warning: Task "bower-install-simple:def" failed. Use --force to continue.
``` 

This is most likely due to a version error/incompatibility issue from manually installing the modules.

**Comment by benkaiser** [comment]
Did you run a plain `npm install` before grunt? Because you need to do that
and it will automatically install all those packages for you.

**Comment by mnzt** [comment]
I was running NPM v2.4 beforehand, an update to v3.3.12 fixed all the issues. Maybe you could update the readme to state that NPM 3 is a requirement?

**Comment by benkaiser** [comment]
So `npm install` was broken on NPM v2.4? That seems pretty odd, the readme
has barely changed at all since then...

**Comment by mnzt** [comment]
Seems to be the case, I think it may just be down to how NPM handles dependencies in the new version vs the old.

**Comment by benkaiser** [comment]
Hmmm... So when you installed nodejs on your fresh Ubuntu box, did it come
with 2.4 by default? Was that the latest it had in the repos or something?

I just hesitate to update the readme if the issue is not using the latest
package versions.

**Comment by mnzt** [comment]
It was a fresh box running Node v4.2.4 (LTS), with NPM 2.14.12 (my apologies for the incorrect version).

**Comment by benkaiser** [comment]
All good. Yeah I might add a note about running the latest versions then.
You're welcome to send me a PR with that change if you'd like (just put it
in the dependencies section).
